spring:
  redis:
    database: 0
    # Redis服务器地址
    host: 101.200.215.115
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 2000

    ##连接池最大连接数（使用负值表示没有限制） 默认8
    lettuce:
      pool:
        max-active: 8
    ## 连接池中的最大空闲连接 默认8
    #spring.redis.lettuce.pool.max-idle=8
    ## 连接池中的最小空闲连接 默认0
    #spring.redis.lettuce.pool.min-idle=0
    ## 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
    #spring.redis.lettuce.pool.max-wait=-1